version: '2'

networks:
  diplo_network:
    #external:
    #  name: nginxproxynetwork
    external: false

services:
  diplo_app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    environment:
      - VIRTUAL_HOST=diplo.sd.di.huc.knaw.nl
    volumes:
      - ./data:/data
    networks:
      - diplo_network
    ports:
      - 80:80